# 关于up.py

selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir



这个网站可能因为多次访问出现被对方服务器封ip的情况，过几分钟再运行就行了。

这个网站的服务器和验证码经常挂。

![image-20190721170442946](image/image-20190721170442946.png)